name: Test compose file
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_PW: "testPw1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test compose file
        uses: isbang/compose-action@v2.4.0
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            db01
            matter01
      - name: maybe should run shell script to test
        run: ./test-server.sh
