name: Test compose file
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test compose file
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            db01
            matter01
      - name: maybe should run shell script to test
        run: echo "Hello, Test"
      # - name: Tests
      #   uses: cloudposse/github-action-docker-compose-test-run@v0.1.2
      #   with:
      #     file: docker-compose.yml
      #     #service: app
      #     command: test/unit-tests.sh
